; extends

(
	((comment) @_comm (#match? @_comm "[Ss][Qq][Ll]"))
	.
	[
		((string_literal_fragment) @injection.content)
		(_ ((string_literal_fragment) @injection.content))
		(_ (_ ((string_literal_fragment) @injection.content)))
		(_ (_ (_ ((string_literal_fragment) @injection.content))))
		(_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))
		(_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))
		(_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))
		(_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content))))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((string_literal_fragment) @injection.content)))))))))))))))))))))
	]
	(#set! injection.language "sql")
)

(
	((comment) @_comm (#match? @_comm "[Ss][Qq][Ll]"))
	.
	[
		((verbatim_string_literal) @injection.content)
		(_ ((verbatim_string_literal) @injection.content))
		(_ (_ ((verbatim_string_literal) @injection.content)))
		(_ (_ (_ ((verbatim_string_literal) @injection.content))))
		(_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))
		(_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))
		(_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))
		(_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content))))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((verbatim_string_literal) @injection.content)))))))))))))))))))))
	]
	((#offset! @injection.content 0 2 0 -1))
	(#set! injection.language "sql")
)

(
	((comment) @_comm (#match? @_comm "[Ss][Qq][Ll]"))
	.
	[
		((raw_string_literal) @injection.content)
		(_ ((raw_string_literal) @injection.content))
		(_ (_ ((raw_string_literal) @injection.content)))
		(_ (_ (_ ((raw_string_literal) @injection.content))))
		(_ (_ (_ (_ ((raw_string_literal) @injection.content)))))
		(_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))
		(_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))
		(_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content))))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((raw_string_literal) @injection.content)))))))))))))))))))))
	]
	((#offset! @injection.content 0 3 0 -3))
	(#set! injection.language "sql")
)


(
	((comment) @_comm (#match? @_comm "[Ss][Qq][Ll]"))
	.
	[
		((interpolated_verbatim_string_text) @injection.content)
		(_ ((interpolated_verbatim_string_text) @injection.content))
		(_ (_ ((interpolated_verbatim_string_text) @injection.content)))
		(_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))
		(_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))
		(_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))
		(_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))
		(_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content))))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_verbatim_string_text) @injection.content)))))))))))))))))))))
	]
	((#offset! @injection.content 0 3 0 -3))
	(#set! injection.conbined)
	(#set! injection.language "sql")
)

(
	((comment) @_comm (#match? @_comm "[Ss][Qq][Ll]"))
	.
	[
		((interpolated_string_text) @injection.content)
		(_ ((interpolated_string_text) @injection.content))
		(_ (_ ((interpolated_string_text) @injection.content)))
		(_ (_ (_ ((interpolated_string_text) @injection.content))))
		(_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))
		(_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))
		(_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))
		(_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content))))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_string_text) @injection.content)))))))))))))))))))))
	]
	(#set! injection.conbined)
	(#set! injection.language "sql")
)

(
	((comment) @_comm (#match? @_comm "[Ss][Qq][Ll]"))
	.
	[
		((interpolated_raw_string_text) @injection.content)
		(_ ((interpolated_raw_string_text) @injection.content))
		(_ (_ ((interpolated_raw_string_text) @injection.content)))
		(_ (_ (_ ((interpolated_raw_string_text) @injection.content))))
		(_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))
		(_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))
		(_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))
		(_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content))))))))))))))))))))
		(_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ (_ ((interpolated_raw_string_text) @injection.content)))))))))))))))))))))
	]
	(#set! injection.conbined)
	(#set! injection.language "sql")
)
