// Package tmux drives a dedicated, isolated tmux server (its own socket) that
// hosts Claude sessions. Using a separate socket means claude-mux can run
// happily nested inside another tmux without any binding or session conflict.
package tmux

import (
	"crypto/sha1"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"claude-mux/internal/claude"
	"claude-mux/internal/paths"
)

// DefaultSocket is the tmux -L socket name used unless overridden.
const DefaultSocket = "claude-mux"

// sessionIDOption is the tmux window option that records which Claude session a
// window is running. It is what lets the picker tell running sessions apart and
// jump straight to their window.
const sessionIDOption = "@claude_session_id"

// Server represents the isolated tmux server on a given socket.
type Server struct {
	Socket  string
	BinPath string // absolute path to the claude-mux binary, baked into bindings
}

// New returns a Server for the socket named by $CLAUDE_MUX_SOCKET, falling back
// to DefaultSocket.
func New() *Server {
	sock := os.Getenv("CLAUDE_MUX_SOCKET")
	if sock == "" {
		sock = DefaultSocket
	}
	self, _ := os.Executable()
	return &Server{Socket: sock, BinPath: self}
}

// args prepends the socket selector to a tmux argument list.
func (s *Server) args(rest ...string) []string {
	return append([]string{"-L", s.Socket}, rest...)
}

// run executes a tmux command and returns trimmed stdout.
func (s *Server) run(rest ...string) (string, error) {
	cmd := exec.Command("tmux", s.args(rest...)...)
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("tmux %s: %s", strings.Join(rest, " "), strings.TrimSpace(string(ee.Stderr)))
		}
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// Slug derives a stable, tmux-safe session name from a project directory:
// its basename plus a short hash of the full path for disambiguation.
func Slug(dir string) string {
	base := filepath.Base(dir)
	var b strings.Builder
	for _, r := range base {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	sum := sha1.Sum([]byte(dir))
	return b.String() + "-" + hex.EncodeToString(sum[:])[:6]
}

// launchCmd builds the shell-command tmux runs in a window: it goes through
// `claude-mux run` so the window records its session id, then execs Claude.
func (s *Server) launchCmd(dir, resumeID string) string {
	q := func(v string) string { return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'" }
	cmd := fmt.Sprintf("exec %s run --dir %s", q(s.BinPath), q(dir))
	if resumeID != "" {
		cmd += " --resume " + q(resumeID)
	}
	return cmd
}

// configPath is where the generated, isolated tmux config lives.
func configPath() string {
	return filepath.Join(paths.CacheDir(), "tmux.conf")
}

// writeConfig (re)generates the isolated tmux configuration. The Claude session
// tmux deliberately loads none of the user's config: the only keys bound are
// claude-mux's own chords under the C-x prefix. binPath and socket are baked in
// so the bindings work regardless of $PATH inside the server.
func writeConfig(binPath, socket string) (string, error) {
	if err := os.MkdirAll(paths.CacheDir(), 0o755); err != nil {
		return "", err
	}
	conf := fmt.Sprintf(`# Generated by claude-mux. Do not edit; it is rewritten on launch.
set -g prefix C-x
set -g prefix2 None
set -g status off
# Claude Code probes these on startup (tmux show -Av mouse / -gv focus-events)
# and nags with a "tmux detected ..." hint whenever they are not "on": mouse on
# gives it wheel scrollback, focus-events on lets it see terminal focus changes.
set -g mouse on
set -g focus-events on
set -g escape-time 10
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"

# Forward extended keys (CSI-u) so Claude can tell C-h from Backspace, etc.
set -g extended-keys on
set -as terminal-features '*:extkeys'

# Frame the floating picker with a rounded border so it stands out, but keep its
# interior on the terminal's default colours so it follows the system theme.
set -g popup-border-lines rounded
set -g popup-border-style "fg=blue"
set -g popup-style "bg=default,fg=default"

# When a Claude window ends (the process exits), detach the client so claude-mux
# exits back to the shell, while any other sessions keep running in the
# background. Popups do not fire this hook, so opening the picker is safe.
set-hook -g window-unlinked "detach-client"

# Isolated: strip every default binding, then add only our chords.
unbind -a -T prefix
unbind -a -T root

# C-x C-x sends a literal C-x through to Claude.
bind -T prefix C-x send-prefix
# C-x l : floating list of all Claude sessions for this project. The project is
# resolved from the session environment ($CLAUDE_MUX_PROJECT_DIR, which the popup
# inherits) rather than a format inside the shell-command, because tmux passes
# the shell-command verbatim without expanding #{...}. -d sets the popup's start
# directory (and does expand) as a belt-and-suspenders.
bind -T prefix l display-popup -d "#{@claude_project_dir}" -w 90%% -h 85%% -E "'%s' list --socket '%s'"
# C-x r : floating remote-control (claude rc) toggle for this project.
bind -T prefix r display-popup -d "#{@claude_project_dir}" -w 60%% -h 40%% -E "'%s' rc --socket '%s'"
# C-x n : start a fresh Claude session in a new window (current keeps running).
# Like the l/r bindings, the project is resolved from the session environment
# ($CLAUDE_MUX_PROJECT_DIR, which the new window inherits) rather than a #{...}
# format inside the shell-command: tmux passes the shell-command verbatim and
# does not expand formats there, so an embedded --dir '#{@claude_project_dir}'
# would reach run as a literal path, fail to chdir, and drop the whole session.
bind -T prefix n new-window -c "#{@claude_project_dir}" -n claude "exec '%s' run"
# C-x u : float the current Claude usage (limits). The command stays up until
# the user presses q (claude-mux usage blocks on a keypress), so -E can close
# the popup on exit without it flashing away the instant claude prints.
bind -T prefix u display-popup -d "#{@claude_project_dir}" -w 80%% -h 75%% -E "'%s' usage"
# C-x d : detach and leave everything running in the background.
bind -T prefix d detach-client
`, binPath, socket, binPath, socket, binPath, binPath)

	path := configPath()
	if err := os.WriteFile(path, []byte(conf), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// EnsureSession makes sure the isolated server is running and has a session for
// dir (creating one that launches Claude if needed), records the project
// directory on the session, and refreshes the bindings. It does not attach.
func (s *Server) EnsureSession(dir string) (string, error) {
	conf, err := writeConfig(s.BinPath, s.Socket)
	if err != nil {
		return "", err
	}
	slug := Slug(dir)

	// Only create the session if it does not already exist. (We deliberately
	// avoid `new-session -A`: on an existing session -A behaves like
	// attach-session, which tries to grab a terminal and fails here because this
	// runs with captured, non-tty stdio.) -f applies our config when this call
	// is what first starts the server.
	if !s.hasSession(slug) {
		if _, err := s.run("-f", conf, "new-session", "-d", "-s", slug, "-c", dir, s.launchCmd(dir, "")); err != nil {
			return "", err
		}
	}
	s.tagProject(slug, dir)
	// Re-source the config so bindings exist even if the server pre-existed.
	_, _ = s.run("source-file", conf)
	return slug, nil
}

// tagProject records the project directory on a session, both as a tmux option
// (for the -c in bindings) and in the session environment (so the popup and any
// launched process resolve the same project and Claude config dir).
func (s *Server) tagProject(slug, dir string) {
	_, _ = s.run("set-option", "-t", slug, "@claude_project_dir", dir)
	_, _ = s.run("set-environment", "-t", slug, "CLAUDE_MUX_PROJECT_DIR", dir)
	_, _ = s.run("set-environment", "-t", slug, "CLAUDE_CONFIG_DIR", paths.ClaudeConfigDir())
}

// Attach replaces the current process with a tmux client attached to slug.
func (s *Server) Attach(slug string) error {
	tmuxPath, err := exec.LookPath("tmux")
	if err != nil {
		return err
	}
	argv := s.args("attach-session", "-t", slug)
	return syscall.Exec(tmuxPath, append([]string{tmuxPath}, argv...), os.Environ())
}

// RunningSessions returns a map of Claude session id -> tmux target
// ("session:window") for every window currently hosting a session. This is how
// the picker knows what is live and where to jump.
func (s *Server) RunningSessions() map[string]string {
	out, err := s.run("list-windows", "-a", "-F",
		"#{session_name}:#{window_index}\t#{"+sessionIDOption+"}")
	if err != nil {
		return nil
	}
	result := make(map[string]string)
	for _, ln := range strings.Split(out, "\n") {
		if ln == "" {
			continue
		}
		f := strings.SplitN(ln, "\t", 2)
		if len(f) != 2 || f[1] == "" {
			continue
		}
		result[f[1]] = f[0]
	}
	return result
}

// CurrentSessionID returns the Claude session id tagged on the window the
// current client is focused on — i.e. the pane the picker popup was floated
// over. A popup runs on its own throwaway pane (so $TMUX_PANE is useless here)
// but a no-target display-message resolves against the client's active window,
// which is the underlying Claude window. Returns "" when it cannot be
// determined (not inside our server, or the window is untagged).
func (s *Server) CurrentSessionID() string {
	out, err := s.run("display-message", "-p", "#{"+sessionIDOption+"}")
	if err != nil {
		return ""
	}
	return out
}

// TagWindow records sessionID on the window containing paneTarget (usually
// $TMUX_PANE), so RunningSessions can find it later.
func (s *Server) TagWindow(paneTarget, sessionID string) error {
	_, err := s.run("set-option", "-w", "-t", paneTarget, sessionIDOption, sessionID)
	return err
}

// WindowSessionID returns the Claude session id currently tagged on the window
// containing paneTarget, or "" when it is untagged or cannot be resolved.
func (s *Server) WindowSessionID(paneTarget string) string {
	out, err := s.run("show-options", "-wqv", "-t", paneTarget, sessionIDOption)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(out)
}

// hasSession reports whether a session named slug exists.
func (s *Server) hasSession(slug string) bool {
	_, err := s.run("has-session", "-t", slug)
	return err == nil
}

// Focus brings the window at target ("session:window") to the foreground,
// switching the current client to that session first so it also works for a
// session belonging to another project (the --all case).
func (s *Server) Focus(target string) error {
	sess := target
	if i := strings.IndexByte(target, ':'); i >= 0 {
		sess = target[:i]
	}
	_, _ = s.run("switch-client", "-t", sess)
	_, err := s.run("select-window", "-t", target)
	return err
}

// ResumeInProject opens (or creates the project session for) a window that
// resumes the given Claude session id in dir, then switches the client to it.
func (s *Server) ResumeInProject(dir, sessionID string) error {
	slug := Slug(dir)
	if s.hasSession(slug) {
		if _, err := s.run("new-window", "-t", slug, "-c", dir, "-n", "claude", s.launchCmd(dir, sessionID)); err != nil {
			return err
		}
	} else {
		if _, err := s.run("new-session", "-d", "-s", slug, "-c", dir, s.launchCmd(dir, sessionID)); err != nil {
			return err
		}
		s.tagProject(slug, dir)
	}
	_, err := s.run("switch-client", "-t", slug)
	return err
}

// KillWindow terminates the Claude window at target ("session:window"). The
// window-unlinked hook (which auto-detaches on Claude exit) is suppressed around
// the kill so removing a session from the picker doesn't drop the client; it is
// restored immediately after.
func (s *Server) KillWindow(target string) error {
	_, _ = s.run("set-hook", "-gu", "window-unlinked")
	_, err := s.run("kill-window", "-t", target)
	_, _ = s.run("set-hook", "-g", "window-unlinked", "detach-client")
	return err
}

// KillProject kills the tmux session (and thus every running Claude window) for
// dir. It is a no-op when no such session exists. Returns whether one was killed.
func (s *Server) KillProject(dir string) (bool, error) {
	slug := Slug(dir)
	if !s.hasSession(slug) {
		return false, nil
	}
	_, err := s.run("kill-session", "-t", slug)
	return err == nil, err
}

// KillAll tears down the entire isolated server (every project's sessions). It
// is a no-op when the server is not running.
func (s *Server) KillAll() error {
	if _, err := s.run("kill-server"); err != nil {
		// kill-server errors when nothing is running; that is fine.
		if strings.Contains(err.Error(), "no server running") {
			return nil
		}
		return err
	}
	return nil
}

// NewWindowFresh opens a new window running a fresh Claude session in dir.
func (s *Server) NewWindowFresh(dir string) error {
	slug := Slug(dir)
	if !s.hasSession(slug) {
		if _, err := s.run("new-session", "-d", "-s", slug, "-c", dir, s.launchCmd(dir, "")); err != nil {
			return err
		}
		s.tagProject(slug, dir)
		_, err := s.run("switch-client", "-t", slug)
		return err
	}
	_, err := s.run("new-window", "-t", slug, "-c", dir, "-n", "claude", s.launchCmd(dir, ""))
	return err
}

// usageSocket is the throwaway tmux socket used to render `claude /usage`
// headlessly. It is deliberately a *different* socket from the claude-mux
// server so the render never creates a window, session or picker entry there.
const usageSocket = "claude-mux-usage"

// CaptureUsage renders Claude's interactive `/usage` panel (the one with the
// coloured progress bars) in a throwaway, off-screen tmux pane sized cols×rows,
// then returns the captured screen with its ANSI colours preserved so a popup
// can print it verbatim. `/usage` draws as a full-screen overlay, so the whole
// pane is the panel — no composer to strip.
//
// The render runs on its own tmux socket (see usageSocket) which is torn down
// before returning, so it never touches the claude-mux server. It polls until
// the bars have painted (or times out), because Claude takes a moment to boot.
func CaptureUsage(dir string, cols, rows int) (string, error) {
	run := func(args ...string) (string, error) {
		out, err := exec.Command("tmux", append([]string{"-L", usageSocket}, args...)...).Output()
		return string(out), err
	}
	// Start clean in case a previous render was left behind, and always tear the
	// scratch server down on the way out.
	_, _ = run("kill-server")
	defer func() { _, _ = run("kill-server") }()

	// Pass Claude's config dir through explicitly: a fresh tmux server does not
	// inherit arbitrary env vars, and the render must read the same transcripts.
	newArgs := []string{"new-session", "-d", "-s", "u",
		"-x", strconv.Itoa(cols), "-y", strconv.Itoa(rows), "-c", dir}
	if cfg := os.Getenv("CLAUDE_CONFIG_DIR"); cfg != "" {
		newArgs = append(newArgs, "-e", "CLAUDE_CONFIG_DIR="+cfg)
	}
	newArgs = append(newArgs, `claude "/usage"`)
	if _, err := run(newArgs...); err != nil {
		return "", err
	}

	var last string
	for i := 0; i < 60; i++ {
		out, err := run("capture-pane", "-p", "-e", "-t", "u")
		if err == nil {
			last = out
			// The panel has painted once a progress bar (█) and a "% used"
			// label are both on screen.
			if strings.Contains(out, "% used") && strings.Contains(out, "█") {
				return strings.TrimRight(out, "\n"), nil
			}
		}
		time.Sleep(250 * time.Millisecond)
	}
	return strings.TrimRight(last, "\n"), fmt.Errorf("timed out waiting for usage to render")
}

// rcSuffix is appended to a project's slug to name its dedicated tmux session
// hosting the Claude remote-control (`claude rc`) server. Keeping rc in its own
// session (rather than a window in the project session) means an rc-enabled
// project can run its server in the background without a stray Claude window,
// and it never shows up in the session picker.
const rcSuffix = "-rc"

// rcSlug returns the tmux session name hosting rc for dir.
func (s *Server) rcSlug(dir string) string { return Slug(dir) + rcSuffix }

// IsRunning reports whether the isolated tmux server is currently up.
func (s *Server) IsRunning() bool {
	_, err := s.run("list-sessions")
	return err == nil
}

// HasRC reports whether the remote-control server is running for dir.
func (s *Server) HasRC(dir string) bool {
	return s.hasSession(s.rcSlug(dir))
}

// StartRC brings up `claude rc` for dir in its own detached tmux session. It is
// a no-op when one is already running.
//
// `claude rc` is launched fully non-interactively: --spawn=same-dir skips the
// spawn-mode chooser prompt, and the directory is pre-trusted (see
// claude.EnsureTrusted) so it does not stall on the workspace trust dialog.
// Either prompt would otherwise leave the server blocked, so the rc session
// would look "on" while doing nothing.
func (s *Server) StartRC(dir string) error {
	slug := s.rcSlug(dir)
	if s.hasSession(slug) {
		return nil
	}
	if err := claude.EnsureTrusted(dir); err != nil {
		return err
	}
	conf, err := writeConfig(s.BinPath, s.Socket)
	if err != nil {
		return err
	}
	if _, err := s.run("-f", conf, "new-session", "-d", "-s", slug, "-c", dir, "exec claude rc --spawn=same-dir"); err != nil {
		return err
	}
	s.tagProject(slug, dir)
	_, _ = s.run("source-file", conf)
	return nil
}

// StopRC tears down the remote-control session for dir. The window-unlinked
// hook (auto-detach on window close) is suppressed around the kill so stopping
// rc never drops the current client. It is a no-op when rc is not running.
func (s *Server) StopRC(dir string) error {
	slug := s.rcSlug(dir)
	if !s.hasSession(slug) {
		return nil
	}
	_, _ = s.run("set-hook", "-gu", "window-unlinked")
	_, err := s.run("kill-session", "-t", slug)
	_, _ = s.run("set-hook", "-g", "window-unlinked", "detach-client")
	return err
}

// FocusRC switches the current client to dir's remote-control session.
func (s *Server) FocusRC(dir string) error {
	slug := s.rcSlug(dir)
	if !s.hasSession(slug) {
		return fmt.Errorf("remote control is not running for this project")
	}
	_, err := s.run("switch-client", "-t", slug)
	return err
}

// InsideOurServer reports whether the current process is running inside a client
// of this server (i.e. $TMUX points at our socket), which tells the picker
// whether it can drive tmux or must fall back to launching Claude directly.
func (s *Server) InsideOurServer() bool {
	t := os.Getenv("TMUX")
	if t == "" {
		return false
	}
	// $TMUX is "socket_path,pid,session"; the socket path ends in the name.
	sockPath := strings.Split(t, ",")[0]
	return filepath.Base(sockPath) == s.Socket
}
